name: RpCore
version: '0.0.17'
main: org.Rpcore.Rpplugin.Main
api-version: '1.21'
commands:
  setrole:
    permission: rpcore.setrole
  looc:
  ooc:
  rpname:
  setdesc:
  setage:
  viewdesc:
    permission: rpcore.viewdesc , rpcore.viewdesc.admin
    permissions:
      - rpcore.viewdesc
      - rpcore.viewdesc.admin